### ISSUE TITLE
Plugin doesn't recognize d.ts files (I think)

### ISSUE THREAD

**Issue by jonyt** [Phaiax/ArcticTypescript#1]
I'm trying to work with some d.ts files. My file compiles ok with `tsc`, but the plugin doesn't recognize the definitions. Here's the file:

    ///<reference path="jquery.d.ts"/>
    ///<reference path="underscore.d.ts"/>
    ///<reference path="backbone.d.ts"/>

    import Backbone = require("backbone");

    class Animal extends Backbone.Model {
	
	    initialize(attributes: any) {
	        	this.set('name', 'joe');
	    }
    }

The error is `Module cannot be aliased to a non-module type`. This is Sublime Text build 3065 on Ubuntu 14.04.

**Comment by Phaiax** [comment]
I have seen this error message but I just cant remember the reason why. Have you tried to restart sublime?

I created an example project with your file:
https://github.com/Phaiax/ArcticTypescript/tree/improvements/tests/DTSTest

Can you tell me the difference between your project and mine?

**Comment by jonyt** [comment]
OK, my bad. I didn't define the project root correctly in the `.sublimets` file.
