### ISSUE TITLE
error highlighting in gutter 

### ISSUE THREAD

**Issue by druppy** [Phaiax/ArcticTypescript#11]
Hi ...

I am very happy for this new TS3 plugin, it works wonders most of the time, but a few things don't seems to work.

The SublimeLinter errors in the gutter provides small symbols when I make an error in the TS code as expected, but I can't get any hint as to what kind of error this is. I have tried all kind of clicking and mouse-over, but it only just end up marking the line for clipboard clipping :-(
When I use a js-lint plugin the gutter icons provide nice descriptions in the status bar, so it is working for other plugins.

The other thing are the alt-shift-e function. It works only if i provide a additional h,k,j,l char afterwards but not as it self, is that supposed to work that way ?

/BL

**Comment by Phaiax** [comment]
Hey druppy

Thank you for using this Plugin.

First: gutter? Is this the name for the column with the line numbers and icons?

Second: You need to look at the status bar at the bottom while the cursor is above the error. Sublime does not allow for tooltips on gutter icons or marked text. But the developer of sublime has been asked for this feature several times in the official sublime forum. (Oh I read that js-lint is using the status bar. Errors should show up there (they do here with my sublime). Which os and which sublime version are you using?)

Third: No, it's not. But I have verified this behaviour. It also helps to press e twice currently. This is a bug which I am going to fix now :

- Phaiax

**Comment by druppy** [comment]
Yeps, I think that "gutter" is the name of the part that may (or may not) contain both the line number and the linter marks and other (like vcs).

I have been looking at the status bar, but to no use :-(

I use 64 bit Debian Jessie, sublime 3 3066 (dev) on both an pure Intel platform (i5 laptop) and while using an NVIDIA card (to exclude OpenGL things).

Cool that the error window action can be fixed fast, could it be possible top place in the button as the "build" window, or are there some limitation related to that ?

**Comment by Phaiax** [comment]
Hey.

Error window shortcut:

Because Sublime is waiting for the second keystroke for the Shortcuts Shift+Alt+e,h .. it will not excute Shift+Alt+e. I could just update the Readme and change the error window shortcut to Shift+Alt+e,e or i could change the four other shortcuts. What would you prefer?

Error display:

Okay, you are using the nightly build. Thats not a priority then. How about using 3065? Or is there any feature you defenitely need?

**Comment by druppy** [comment]
Hi

I think a readme fix is ok for me at least, I just did think so far :-)

And you maybe right, I should properly just use 3065, as I just used 3066 out of curiosity (I am fairly new as a sublime user).
