### ISSUE TITLE
A process of typescript project initializing is endless

### ISSUE THREAD

**Issue by stan0227** [Phaiax/ArcticTypescript#14]
When I create a new typescript project, the process of typescript project initializing is endless. Even I try to open the folder as "example/sublimets" or "example/sublimeproject".
Any idea?

**Comment by Phaiax** [comment]
version/os?

**Comment by stan0227** [comment]
Hi Phaiax,
My OS version is Win7 sp1 64bits. And Sublime Text vesrion is "stable channel, build 3065".
I am a whole new user for Sublime Text, so my Sublime Text is unregistered.

**Comment by Phaiax** [comment]
Okay, i could reproduce the error in win 8. I think the problem is the missing nodejs path.

There should definiely appear a message to inform the user.

Do you have installed nodejs?

**Comment by stan0227** [comment]
Yes. I have installed nodejs. The version is v0.10.32. And the Windows environment PATH is also be set. By the way, my Sublime Text is portable version.

**Comment by stan0227** [comment]
What "path" should I set in "node_path" of the setting? Indicating the node.exe or just the nodejs root folder?

**Comment by Phaiax** [comment]
Okay, my problem was that nodejs has inserted its path to %PATH% but for some reason the most recent PATH was not available in the shells/commandline/..

If you just installed node, you need to logout your windows account (and login again).

There is a new version of ArcticTypescript which then displays an error message to the user.
