### ISSUE TITLE
All commands or features aren't working

### ISSUE THREAD

**Issue by stan0227** [Phaiax/ArcticTypescript#15]
OS: Win 7 sp1 64bits
ST3: Build 3065

I can see the syntax coloring on .ts file.

But all the commands or features like: auto completion( it just shows terms in a file ), error highlighting, syntax highlighting, refactoring, etc, aren't working.

**Comment by Phaiax** [comment]
Have you created a project? What are your project settings?

https://www.youtube.com/watch?v=35J6ugnLag0

**Comment by stan0227** [comment]
Hi Phaiax,

Thanks to your youtube video. Cool! I flow the video and success to using the feature of ArcticTypescript. Great Job. Thanks a lot.
