### ISSUE TITLE
TypeScript 1.4

### ISSUE THREAD

**Issue by yukulele** [Phaiax/ArcticTypescript#16]
ArcticTypescript is not compatible with TypeScript 1.4 new features:

Union Type:

```typescript
function foo(bar: string|number ){ /* */ }
```
Template Strings:

```typescript
return `My name is ${firstname} ${lastname.toUpperCase()}`
```
And more...
http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx

**Comment by Phaiax** [comment]
https://github.com/clausreinke/typescript-tools

This is what ArcticTypescript is using and what defines the binding to the actual used typescript version. It seems like the author clausreinke is planning to update to Typescript 1.4:

https://github.com/clausreinke/typescript-tools/issues/39

But this is a bunch of work as you can see, so don't expect this to be done immediately.

**Comment by pocesar** [comment]
:+1:

**Comment by IlanFrumer** [comment]
:+1:

**Comment by Phaiax** [comment]
I have included the new typescript-tools and the dev branch now supports typescript 1.5.

My current problem is the configuration of the typescript services (ES5/6, ..). With typescript 1.5, there another compiler configuration option via a tsconfig.json file has been introduced, and the typescript-services support this file as well:

https://github.com/TypeStrong/tsconfig

I would like to move the configuration from the .sublime-project and .sublimets file to only support tsconfig.json. The config in this tsconfig.json file would be used from the codecompletions stuff as well as from the included build system. (and other editors too)

But they are still investigating and changing the style of tsconfig.json (file blob, ..):

https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+tsconfig

I'm not completely sure on where to put the other settings (build_on_save, ..) (most of them are user related, so they can move into .sublime-project or some other config file in the sublime config folder. 

But where will i put the pre_processing_commands and post_processing_commands? I'm not sure if i should put this into tsconfig.json or drop support for these options.

IMO, very simple projects do not need these options, and for bigger and more complicated projects they are not sufficient. Those projects will use grunt/jake/make anyway, so there would be no need for a build system with pre_processing_commands support in ArcticTypescript.

The other thing is, I would recommend to use tsc with --watch anyway. 

<b>If you do not raise your hand, I may drop those options.</b>

As soon as I have decided what to do, I will continue to work on.

**Comment by AdamPD** [comment]
Strange - whenever I checkout the dev branch, I start getting errors.

**Comment by IlanFrumer** [comment]
F1 not working , I get this error:

Traceback (most recent call last):
  File "/home/ilan/.config/sublime-text-3/Packages/ArcticTypescript/lib/system/AsyncCommand.py", line 148, in <lambda>
    sublime.set_timeout(lambda:self.result_callback(tss_answer, **self.callback_kwargs),000)
  File "/home/ilan/.config/sublime-text-3/Packages/ArcticTypescript/lib/Commands.py", line 64, in async_react
    liste = types['docComment'].split('\n')+[kind+' '+types['fullSymbolName']+' '+types['type']]
KeyError: 'fullSymbolName'

**Comment by Phaiax** [comment]
Current dev branch is next_big_thing

Some todos to do, but its almost finished

**Comment by IlanFrumer** [comment]
Good job. Everything works great now. :+1:

**Comment by Phaiax** [comment]
new version 0.6.0 is out. If you switched to next_big_thing, i would recommend you to go back to package control, since next_big_thing is not active anymore.

One thing what is missing is syntax highlighting for `let`, `type` and template strings, but this will be implemented in the next version.

I will close this for now.
