### ISSUE TITLE
Build fails if output_dir_path setting contains a space.

### ISSUE THREAD

**Issue by Raiizn** [Phaiax/ArcticTypescript#17]
So far I've been very happy with this plugin, but I ran into this error lately. Normally a space in the outDir wouldn't be an issue, as you could enclose the path with '', but I am using a relative path to work on multiple computers. On one of the machines I work on, my Windows user directory contains a space, and so the build fails.

From the log, it appears that the outDir option is not enclosed in 's when building.

**Comment by Phaiax** [comment]
okay, i'll take a look in the next days

**Comment by Phaiax** [comment]
verified

**Comment by Phaiax** [comment]
https://github.com/Phaiax/ArcticTypescript/commit/b07b8e0dd585a8a356e103b41c78fee2ca6d3932
solves it.

Thank you for helping

**Comment by Raiizn** [comment]
Thanks for the quick response! I'm happy to be of help.
