### ISSUE TITLE
No auto completion and reference file issues in ST3

### ISSUE THREAD

**Issue by Roam-Cooper** [Phaiax/ArcticTypescript#20]
I don't get any auto completion at all with AT as well as I have reference files for AngularJS and I am using AngularJS declarations in my file.

Compiling with TSC via terminal works fine, but in Sublime, AT complains "could not find symbol 'angular'"

I've tried better typescript, I've tried T3S and I've tried ArcticTypescript and none of them work. I am forced to use OSX at work, so it would be nice to find a decent sublime equivalent to the "it just works" Visual Studio that I use at home.

I can provide screenshots/extra information as necessary.

**Comment by Phaiax** [comment]
can you make a non-working example project and upload it to github or somewhere else?

**Comment by Phaiax** [comment]
Closed because of no reaction. Please report again if this problem still occurs with the new version 0.6.0.
