### ISSUE TITLE
Auto completion - angular.d.ts and angular-route.d.ts issue

### ISSUE THREAD

**Issue by danielancines** [Phaiax/ArcticTypescript#23]
Hi,

When I'm using angular.d.ts (borisyankov/DefinitelyTyped) in my project, the auto completion not works. I work in this file, to found the problem. When I comment the line #935 (all(promises: IPromise<any>[]|{ [id: string]: IPromise<any>; }): IPromise<any[]>;) that works fine, but with this line uncommented, auto completion doesn't work.

In Visual Studio 2015 CTP 6 that works fine.

Tested on:
Windows 8.1/Mac OSx/Ubuntu
Sublime Text 3 - build 3065

**Comment by danielancines** [comment]
Hi,

Testing now the angular-route.d.ts, I founded a problem with lines #70, #77 and #89, if I commented this lines and that works fine.
With the original file, only interfaces above IRoute appears in auto completion.

Tested on:
Windows 8.1
Sublime Text 3 - build 3065

**Comment by Phaiax** [comment]
Maybe this problem disappears if I upgrade to the newest version of typescript. (There will be big changes to come, with a new configuration structure and without root files.)

But I am still waiting for the Typescript guys to complete the tsserver feature. A few days ago, they said it will be ~10 days to go. Maybe I should take another look on how far they have come.

**Comment by Phaiax** [comment]
This issue should be resolved with version 0.6.0 (i hope). If the error persists, please report again.
