### ISSUE TITLE
Save as dialog pops up constantly if new file is open

### ISSUE THREAD

**Issue by ecraig12345** [Phaiax/ArcticTypescript#24]
If one of my open files is a new (never saved) file, the "Save As" dialog pops up a lot. Some examples of specific times it pops up are when I close a file and sometimes while I'm in the Ctrl+P dialog (seems to happen after I type an "s" in that dialog??). This never happened to me until I configured a project root for autocompletion. 

The workaround is to always save new files to a temp directory or something, but it's still quite annoying--I tend to leave one or more new files open at all times as "scratch" space.

**Comment by Phaiax** [comment]
I'll take a look

**Comment by IlanFrumer** [comment]
:+1:

**Comment by Phaiax** [comment]
May hopefully be solved with version 0.6.0. Please report again if this issue persists.
