### ISSUE TITLE
Plugin messes up granularity of undo

### ISSUE THREAD

**Issue by ecraig12345** [Phaiax/ArcticTypescript#25]
With the plugin enabled, pressing Ctrl+Z for undo only undoes one character at a time, rather than words or other longer sequences, which is pretty annoying. I only noticed this after configuring autocompletion for the first time, but now it seems to happen even when I don't have autocompletion configured. (By "not configured" I mean the project root is set to a nonexistent file.)

**Comment by Phaiax** [comment]
Oh, thats very annoying, but I didn't know about the default behaviour of sublime. Will be fixed soon.

Am 28. Februar 2015 02:15:17 MEZ, schrieb ecraig12345 <notifications@github.com>:
>With the plugin enabled, pressing Ctrl+Z for undo only undoes one
>character at a time, rather than words or other longer sequences, which
>is pretty annoying. I only noticed this after configuring
>autocompletion for the first time, but now it seems to happen even when
>I don't have autocompletion configured. (By "not configured" I mean the
>project root is set to a nonexistent file.)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Phaiax/ArcticTypescript/issues/25

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phaiax** [comment]
Is fixed.

But outline view is dropped temporarily in the new version because typescript-tools has dropped this functionality as well.
