### ISSUE TITLE
Can't build project in ArcticTypescript 0.5.2

### ISSUE THREAD

**Issue by belohlavek** [Phaiax/ArcticTypescript#27]
The error:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "C:\Users\Daniel Main\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\lib\Utils.py", line 89, in catcher
    func(*kargs, **kwargs)
  File "C:\Users\Daniel Main\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\lib\Commands.py", line 290, in run
    if not SETTINGS.get('activate_build_system', get_root(filename)):
  File "C:\Users\Daniel Main\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\lib\system\Settings.py", line 29, in get
    return self.projects_type[root].get(get_any_view_with_root(root),token)
  File "C:\Users\Daniel Main\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\lib\system\Project.py", line 42, in get
    return config_data['settings'][token]
KeyError: 'activate_build_system'
```

My .sublimets file is auto generated (with a couple of tweaks that used to work before).
My tsconfig.json is:

```
{
	"compilerOptions": {
        "module": "commonjs",
        "removeComments": true,
        "out": "app.js",
    }
}
```

I really don't know why two config files are necessary, please upload examples on how to use it correctly.

Thanks for reading :)

**Comment by Phaiax** [comment]
you are right, this is not the perfect solution. 
I'm working on it now

**Comment by belohlavek** [comment]
Any updates on how to solve this?

**Comment by Phaiax** [comment]
I haven't done anything else than Arctic Typescript at my computer in the last two days :D (but only a few hours a day)

Currently, i am removing the need for two config files and I am refactoring code (the original author has used globals everywhere, so it was not possible to open two projects in parallel). I hope to finish this today, because I have to start studying for university soon.

This may introduce some bugs, but please submit them and I will fix them quickly.

**Comment by belohlavek** [comment]
Great job so far, your Plugin is the only one that actually worked for me :)

**Comment by Phaiax** [comment]
grr, did not finished today.

current version in the next_big_thing branch

**Comment by belohlavek** [comment]
It's looking pretty awesome. Keep up the good work!

**Comment by Phaiax** [comment]
new version 0.6.0 is out. If you switched to next_big_thing, i would recommend you to go back to package control, since next_big_thing is not active anymore.
