### ISSUE TITLE
Suppressing the nodejs consoles on Windows 8.1 x64

### ISSUE THREAD

**Issue by brakmic** [Phaiax/ArcticTypescript#28]
When a TS-project gets loaded two nodejs console windows are displayed. It would be nice if there was an option to suppress them.

Regards,
Harris

**Comment by belohlavek** [comment]
Same issue on Win7

**Comment by Phaiax** [comment]
hm, never touch a running system .. I will probably fix this now

**Comment by Phaiax** [comment]
0.5.3
