### ISSUE TITLE
Can't get sublime-project to work

### ISSUE THREAD

**Issue by itsmontoya** [Phaiax/ArcticTypescript#29]
I'm able to get the subliments file working fine. When I attempt to copy the example for sublime-project, I am given an error that no subliments nor sublime-project has been created. 

Thoughts?

**Comment by Phaiax** [comment]
Are you using Windows or Linux?

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Phaiax** [comment]
new version 0.6.0 is out -> Configuration has changed, but there is a Wizzard that can help you to create your `tsconfig.json` file.
(the wizzard only appears if it cannot find a `tsconfig.json`)

I will close this for now. Please report again if you still have issues.
