### ISSUE TITLE
F1 and F4 do nothing

### ISSUE THREAD

**Issue by pocesar** [Phaiax/ArcticTypescript#31]
I'm having no popup or "go to" when pressing either F1 or F4. I'm on windows 7, with typescript-tools 1.4.4, typescript 1.5.0 installed. Nothing shows up on the console

**Comment by Phaiax** [comment]
Hm, I do not have windows 7 available now, but with win 8.1 everything is fine.

After activating your .ts file, does the project have initialized? (There has to be a message in the quick panel and in the python console of sublime).

`typescript-tools 1.4.4` ? Do you mean https://github.com/clausreinke/typescript-tools?
Normally, you do not need to install this for ArcticTypescript. Where and how have you installed it?

**Comment by pocesar** [comment]
I have it installed globally for use with grunt, using `npm install clausreinke/typescript-tools#testing_ts1.4`

yes, it's activated, but I think it's related to #30

**Comment by pocesar** [comment]
Well it was a problem with the previous problem described in #30, it was blocking F1 and F4 from working, seems fine now
