### ISSUE TITLE
"Could not find nodejs" on Mac even though path is set in default settings file

### ISSUE THREAD

**Issue by ecraig12345** [Phaiax/ArcticTypescript#38]
I'm getting the following error on a Mac when setting up a new TypeScript project:
```
Typescript initializion error for : /Users/me/myproject/tsconfig.json
 >>> Could not find nodejs.
I have tried this path: node
Please install nodejs and/or set node_path in the project or plugin settings to the actual executable.
If you are on windows and just have installed node, you first need to logout and login again.
 ArcticTypescript is disabled until you restart sublime.
```

This is my default ArcticTypescript.sublime-settings:
```
{
	"auto_complete" : true,
	"error_on_save_only" : false,
	"activate_build_system" : true,
	"node_path" : "/usr/local/bin/node",
	"tsc_path" : "/Users/me/.node/bin/tsc",
	"build_on_save" : false,
	"pre_processing_commands" : [],
	"post_processing_commands" : [],
	"show_build_file" : false,
}
```

I'm wondering if the problem is actually that a FileNotFoundException is being thrown because some other file isn't found (I haven't set up a project or workspace file yet).

**Comment by pocesar** [comment]
AFAIK it will try to append "node" at the end of the node_path, so it would need to be set to "/usr/local/bin/" (the same goes to tsc I guess)

**Comment by ecraig12345** [comment]
I tried that, and it didn't work. I think it's just picking up completely the wrong path somehow.

**Comment by pocesar** [comment]
does `which node` gives you that path? (just to make sure)

**Comment by ecraig12345** [comment]
Yes. I'm debugging some and it thinks the path is None for some reason. So it's just not looking at the config file.

**Comment by pocesar** [comment]
see if your user sublime settings is using the old TS3 / ArcticTypescript syntax or overriding it, then update it

**Comment by ecraig12345** [comment]
Nope. Something weird is going on when it tries to open the project--it's either not reading the plugin settings file, or not passing it through to the place it's needed.

**Comment by jonatannyberg** [comment]
I am having the same issue. It can not find node at all, I have tried all of the above and it just seems to ignore the settings. I even have the path to node in $PATH so it should not even need the "node_path", i.e. the "I have tried this path: node" it is saying it has tried should work.

**Comment by Phaiax** [comment]
I think these are two issues:

1. I have changed the default way of how node is called on Mac (I tought it would be enough to add /usr/local/bin to PATH, but I guess somehow this does not change anything on how node is called)

2. The setting is ignored.

I'll fix this just now, livecoding.tv/phaiax, just for fun :D

**Comment by Phaiax** [comment]
hope this is fixed now, if not, please reopen

**Comment by Phaiax** [comment]
0.6.2 is out, should be available in 1 hour (restart sublime then)
refer to https://packagecontrol.io/packages/ArcticTypescript and see if the version is already provided via packagecontrol
