### ISSUE TITLE
Remove big example files from the plugin

### ISSUE THREAD

**Issue by aziz** [Phaiax/ArcticTypescript#41]
Why do I need to download a copy of phaser.js which is 2.7 MB to use this plugin?!! This is just an examle. Your plugin is huge 25MB. create a separate branch (i.e. publish or deploy) that only has the plugin code, without the screenshot and examples and add that branch to the Package Manager Repo.

**Comment by Phaiax** [comment]
I'm impressed by myself. Phaser should have not been included, that's a bug.

And there are some other big files I could remove easily. 

#TODO

**Comment by Phaiax** [comment]
resolved with 0.6.5
