### ISSUE TITLE
Request: do project initialization in the background

### ISSUE THREAD

**Issue by ecraig12345** [Phaiax/ArcticTypescript#43]
For large projects, initialization can take a long time (somewhere between 10 and 30 seconds for a project I work on), so it's annoying to have a modal initialization dialog that blocks all operations in the editor. Could the loading be done in the background and the indicator moved to the status bar? 

Some example use cases:
* I previously had ST open with files from my large project. I reopen it to quickly look at an unrelated file. I can't do anything until the large project finishes initializing.
* I want to start looking at or working on something in my large project even before auto-complete and such are available.

**Comment by Phaiax** [comment]
+

**Comment by ecraig12345** [comment]
Thanks so much for all your work on this and for being so responsive about issues!
