### ISSUE TITLE
Build Command Generates no Output (and Proposed Solution)

### ISSUE THREAD

**Issue by joswhite** [Phaiax/ArcticTypescript#48]
<p>When executing the build command (Ctrl+B or "Arctic Typescript: Build" from the Sublime Text command menu), the command "succeeds" but generates no output <code>.js</code> files. The Sublime Text console simply shows the following:</p>
<code>>>> ['node', 'C:\\Users\\JWhite\\AppData\\Roaming\\Sublime Text 3\\Packages\\ArcticTypescript\\bin\\node_modules\\.bin\\tsc', '--project', '.']</code>
<code><<< Finished</code>
<p>After having this issue on my own project, I made a direct copy of one of the example projects on the Arctic Typescript website - <code>examples/using_amd_modules</code> and found the problem persisted when I tried compiling the example code. I also tried reinstalling Node.js (current version - v0.12.2), Sublime Text, and Arctic Typescript, but to no avail. I am using Windows 8 and have <code>npm</code> and the <code>npm typescript-tools</code> package installed.</p>
<p>Running the same build command on the command line gives a possible insight about the problem. The command fails, and we see that somehow the "fail" didn't reach the Sublime Text console. The Node build command expects the given <code>tsc</code> file to be executable code, but instead it is simply a file with the text <code>../typescript/bin/tsc</code>. Apparently the Node build command expects to find executable code in the <code>tsc</code> file rather than simply a relative path to a file containing executable code. Here's my error message, copied directly from the command line:</p>
<code>C:\Users\JWhite\Documents\Typescript>node "C:\\Users\\JWhite\\AppData\\Roaming\\Sublime Text 3\\Packages\\ArcticTypescript\\bin\\node_modules\\.bin\\tsc" --project .</code>
<code>C:\Users\JWhite\AppData\Roaming\Sublime Text 3\Packages\ArcticTypescript\bin\node_modules\.bin\tsc:1</code>
<code>(function (exports, require, module, __filename, __dirname) { ../typescript/bi</code>
<code>                                                              ^</code>
<code>SyntaxError: Unexpected token .</code>
<code>    at exports.runInThisContext (vm.js:73:16)</code>
<code>    at Module._compile (module.js:443:25)</code>
<code>    at Object.Module._extensions..js (module.js:478:10)</code>
<code>    at Module.load (module.js:355:32)</code>
<code>    at Function.Module._load (module.js:310:12)</code>
<code>    at Function.Module.runMain (module.js:501:10)</code>
<code>    at startup (node.js:129:16)</code>
<code>    at node.js:814:3</code>
<p>After belabouring over this problem for many hours, I found a workaround - simply change the command to use the second <code>tsc</code> file instead of trying to get the aforementioned redirect path to compile. The new command compiles on the command line, and it works in the Arctic Typescript Build command as well (note that one must restart Sublime Text before the change will take effect). The nice thing is that even though the above mentioned error did not show up on the Sublime Text console, after making this change, syntax errors during build do appear on the console. Here's the applicable code:</p>
<p>Command line: <code>node "C:\\Users\\JWhite\\AppData\\Roaming\\Sublime Text 3\\Packages\\ArcticTypescript\\bin\\node_modules\\typescript\\bin\\tsc" --project .</code></p>
<p>Arctic Typescript package: Change <code>ArcticTypescript\lib\utils\pathutils.py</code>, line 93 from <code>return os.path.join(package_path, 'bin', 'node_modules', '.bin', 'tsc')</code> to <code>return os.path.join(package_path, 'bin', 'node_modules', 'typescript', 'bin', 'tsc')</code>. Of course, this is a definition library file that gets referenced in the <code>compile.py</code> file, where the above command is executed.</p>
<p>Could we get this bug fixed? Am I missing anything here? Thanks for all your work on the Arctic Typescript project!</p>

**Comment by bhsnll** [comment]
I'm have the same issue. When executing the "Build With..." command (Ctrl+Shift+B) the build seems to work... I'm not quite sure what the difference between the two commands is exactly.

**Comment by joswhite** [comment]
I think you might be talking about the native Sublime Text build option. I noticed that if I do Ctrl+Shift+B or I click on "Build" from the Sublime Text menu, it runs the command indicated by my <code>Typescript.sublimebuild</code> file (simply tsc from the command line) rather than Arctic Typescript's build that compiles my entire project. To run the Arctic Typescript command one must use Ctrl+B or go to the Sublime Text command menu and select "Arctic Typescript: Build".

**Comment by JustGoscha** [comment]
+1 
also doesn't work for me, have to make my own typescript.sublime-build file.

**Comment by Phaiax** [comment]
ill take a look

**Comment by theBull** [comment]
+1 I'm experiencing the same issue. Awesome package, stoked to get it running. Any progress?

**Comment by Phaiax** [comment]
is fixed. Update will be released in the next few hours

**Comment by theBull** [comment]
Thanks! :sunglasses:

**Comment by joswhite** [comment]
It's working for me as well. Thanks!
